### ISSUE TITLE
Falcon Filter Examples

### ISSUE THREAD

**Issue by mobious999** [CrowdStrike/crimson-falcon#36]
Hello,

I've been trying to do a simple query against specific operating system types and it appears the query is not allowed by this os type?

based on the payload 
                'platform': 'linux',
                'os': 'RHEL/CentOS/Oracle',
                'os_version': '8',
just for a sample
sensor_download.get_combined_sensor_installers_by_query(filter=f"platform_name:!'Linux'")

{'status_code': 400, 'headers': {'Server': 'nginx', 'Date': 'Wed, 30 Oct 2024 18:12:09 GMT', 'Content-Type': 'application/json', 'Content-Length': '227', 'Connection': 'keep-alive', 'Content-Encoding': 'gzip', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains, max-age=31536000; includeSubDomains', 'X-Cs-Region': 'us-2', 'X-Cs-Traceid': 'e4af534f-a6d3-44cd-87eb-519a7d486e02', 'X-Ratelimit-Limit': '6000', 'X-Ratelimit-Remaining': '5997'}, 'body': {'meta': {'query_time': 0.01448715, 'powered_by': 'binserv', 'trace_id': 'e4af534f-a6d3-44cd-87eb-519a7d486e02'}, 'errors': [{'code': 400, 'message': "Failed to parse filter expression. ['os' is an unknown property]"}], 'resources': None}}
ERROR:__main__:Query failed with status code 400:

**Comment by mobious999** [comment]
sorry previous test was for just os and then I was trying platform_name

**Comment by carlosmmatos** [comment]
Let me take a look

**Comment by mobious999** [comment]
just tried this filter 

    platform = "linux"
    os = "RHEL/CentOS/Oracle"
    os_version = "8"

    try:
        response = sensor_download.get_combined_sensor_installers_by_query(filter="platform:'{platform}'"+f"+os:'{os}'"+f"+os_version:'{os_version}'")
        print(response)
        if response["status_code"] != 200:
            logger.error(f"Query failed with status code {response['status_code']}: {response.get('errors', '')}")
            return []

{'status_code': 200, 'headers': {'Server': 'nginx', 'Date': 'Wed, 30 Oct 2024 18:26:01 GMT', 'Content-Type': 'application/json', 'Content-Length': '158', 'Connection': 'keep-alive', 'Content-Encoding': 'gzip', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains, max-age=31536000; includeSubDomains', 'X-Cs-Region': 'us-2', 'X-Cs-Traceid': 'af49a20e-d441-45a1-9ab5-802d324b660c', 'X-Ratelimit-Limit': '6000', 'X-Ratelimit-Remaining': '5998'}, 'body': {'meta': {'query_time': 0.147579617, 'powered_by': 'binserv', 'trace_id': 'af49a20e-d441-45a1-9ab5-802d324b660c'}, 'resources': [], 'errors': []}}
WARNING:__main__:No sensors found for filter: <class 'filter'>

**Comment by carlosmmatos** [comment]
can you try this:
```ruby
# Create an instance of the SensorDownloadApi class
sensor_download = Falcon::SensorDownloadApi.new

platform = "linux"
os = "RHEL/CentOS/Oracle"
os_version = "8"
filter = "platform:'#{platform}'+os:'#{os}'+os_version:'#{os_version}'"

begin
  # Get Sensors
  result = sensor_download.get_combined_sensor_installers_by_query({ filter: filter })
  puts result.resources
rescue Falcon::ApiError => e
  puts "Exception when calling SensorDownloadApi->get_combined_sensor_installers_by_query: #{e}"
end
```

Now just making sure - your example kind of looks like Python. Are you looking for the FalconPy SDK or where you looking to use this Ruby SDK?

**Comment by mobious999** [comment]
yes attempting to use falconpy.

**Comment by carlosmmatos** [comment]
Then this is the wrong place ;)

You want to go to https://github.com/CrowdStrike/falconpy

**Comment by mobious999** [comment]
@carlosmmatos  thank you for taking a look.
